apiVersion: v1
kind: Pod
metadata:
  name: northeurope-1
  labels:
    name: northeurope-1
spec:
  containers:
   - name: apache
     env:
     - name: NODE_NAME
       valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
     image: php:7.2-apache
     ports:
     - containerPort: 80
     volumeMounts:
      - mountPath: /var/www/html
        name: html
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: apache-content
  nodeName: aks-nodepool1-38225717-vmss000000

---

apiVersion: v1
kind: Service
metadata:
  name: web-in-northeurope-1
spec:
  type: LoadBalancer
  selector:
    name: northeurope-1
  ports:
  - port: 80
    targetPort: 80