apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-content
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany